<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/18/2017
Description:	Creates the DAL class for  accounts table and respective stored procedures

*/



class Accounts {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $AccountID;
	protected $FirstName;
	protected $LastName;
	protected $Email;
	protected $Password;
	protected $RoleID;
	protected $TeamID;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 7:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6] );
		}
	}


	public function __constructBase() {
		$this->AccountID = 0;
		$this->FirstName = "";
		$this->LastName = "";
		$this->Email = "";
		$this->Password = "";
		$this->RoleID = 0;
		$this->TeamID = 0;
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramAccountID,$paramFirstName,$paramLastName,$paramEmail,$paramPassword,$paramRoleID,$paramTeamID) {
		$this->AccountID = $paramAccountID;
		$this->FirstName = $paramFirstName;
		$this->LastName = $paramLastName;
		$this->Email = $paramEmail;
		$this->Password = $paramPassword;
		$this->RoleID = $paramRoleID;
		$this->TeamID = $paramTeamID;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getAccountID(){
		return $this->AccountID;
	}
	public function setAccountID($value){
		$this->AccountID = $value;
	}
	public function getFirstName(){
		return $this->FirstName;
	}
	public function setFirstName($value){
		$this->FirstName = $value;
	}
	public function getLastName(){
		return $this->LastName;
	}
	public function setLastName($value){
		$this->LastName = $value;
	}
	public function getEmail(){
		return $this->Email;
	}
	public function setEmail($value){
		$this->Email = $value;
	}
	public function getPassword(){
		return $this->Password;
	}
	public function setPassword($value){
		$this->Password = $value;
	}
	public function getRoleID(){
		return $this->RoleID;
	}
	public function setRoleID($value){
		$this->RoleID = $value;
	}
	public function getTeamID(){
		return $this->TeamID;
	}
	public function setTeamID($value){
		$this->TeamID = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setAccountID($row['AccountID']);
		 $this->setFirstName($row['FirstName']);
		 $this->setLastName($row['LastName']);
		 $this->setEmail($row['Email']);
		 $this->setPassword($row['Password']);
		 $this->setRoleID($row['RoleID']);
		 $this->setTeamID($row['TeamID']);
		}
	}


	public function save() {
		if ($this->getAccountID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_Add(?,?,?,?,?,?)');
		$arg1 = $this->getFirstName();
		$arg2 = $this->getLastName();
		$arg3 = $this->getEmail();
		$arg4 = $this->getPassword();
		$arg5 = $this->getRoleID();
		$arg6 = $this->getTeamID();
		$stmt->bind_param('ssssii',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_Update(?,?,?,?,?,?,?)');
		$arg1 = $this->getAccountID();
		$arg2 = $this->getFirstName();
		$arg3 = $this->getLastName();
		$arg4 = $this->getEmail();
		$arg5 = $this->getPassword();
		$arg6 = $this->getRoleID();
		$arg7 = $this->getTeamID();
		$stmt->bind_param('issssii',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$accounts = new Accounts($row['AccountID'],$row['FirstName'],$row['LastName'],$row['Email'],$row['Password'],$row['RoleID'],$row['TeamID']);
				$arr[] = $accounts;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramAccountID,$paramFirstName,$paramLastName,$paramEmail,$paramPassword,$paramRoleID,$paramTeamID) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_accounts_Search(?,?,?,?,?,?,?)');
		$arg1 = Accounts::setNullValue($paramAccountID);
		$arg2 = Accounts::setNullValue($paramFirstName);
		$arg3 = Accounts::setNullValue($paramLastName);
		$arg4 = Accounts::setNullValue($paramEmail);
		$arg5 = Accounts::setNullValue($paramPassword);
		$arg6 = Accounts::setNullValue($paramRoleID);
		$arg7 = Accounts::setNullValue($paramTeamID);
		$stmt->bind_param('issssii',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$accounts = new Accounts($row['AccountID'],$row['FirstName'],$row['LastName'],$row['Email'],$row['Password'],$row['RoleID'],$row['TeamID']);
				$arr[] = $accounts;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
