<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/24/2017
Description:	Creates the DAL class for  permissions table and respective stored procedures

*/



class Permissions {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $PermissionID;
	protected $PermissionName;
	protected $Description;
	protected $CreateDate;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 4:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3] );
		}
	}


	public function __constructBase() {
		$this->PermissionID = 0;
		$this->PermissionName = "";
		$this->Description = "";
		$this->CreateDate = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramPermissionID,$paramPermissionName,$paramDescription,$paramCreateDate) {
		$this->PermissionID = $paramPermissionID;
		$this->PermissionName = $paramPermissionName;
		$this->Description = $paramDescription;
		$this->CreateDate = $paramCreateDate;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getPermissionID(){
		return $this->PermissionID;
	}
	public function setPermissionID($value){
		$this->PermissionID = $value;
	}
	public function getPermissionName(){
		return $this->PermissionName;
	}
	public function setPermissionName($value){
		$this->PermissionName = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getCreateDate(){
		return $this->CreateDate;
	}
	public function setCreateDate($value){
		$this->CreateDate = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setPermissionID($row['PermissionID']);
		 $this->setPermissionName($row['PermissionName']);
		 $this->setDescription($row['Description']);
		 $this->setCreateDate($row['CreateDate']);
		}
	}


	public function save() {
		if ($this->getPermissionID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_Add(?,?,?)');
		$arg1 = $this->getPermissionName();
		$arg2 = $this->getDescription();
		$arg3 = $this->getCreateDate();
		$stmt->bind_param('sss',$arg1,$arg2,$arg3);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_Update(?,?,?,?)');
		$arg1 = $this->getPermissionID();
		$arg2 = $this->getPermissionName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getCreateDate();
		$stmt->bind_param('isss',$arg1,$arg2,$arg3,$arg4);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$permissions = new Permissions($row['PermissionID'],$row['PermissionName'],$row['Description'],$row['CreateDate']);
				$arr[] = $permissions;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramPermissionID,$paramPermissionName,$paramDescription,$paramCreateDate) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_permissions_Search(?,?,?,?)');
		$arg1 = Permissions::setNullValue($paramPermissionID);
		$arg2 = Permissions::setNullValue($paramPermissionName);
		$arg3 = Permissions::setNullValue($paramDescription);
		$arg4 = Permissions::setNullValue($paramCreateDate);
		$stmt->bind_param('isss',$arg1,$arg2,$arg3,$arg4);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$permissions = new Permissions($row['PermissionID'],$row['PermissionName'],$row['Description'],$row['CreateDate']);
				$arr[] = $permissions;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
