<?php
/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/24/2017
Description:	Creates the DAL class for  rolestopermissions table and respective stored procedures

*/



class Rolestopermissions {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $RoleToPermissionID;
	protected $RoleID;
	protected $PermissionID;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 3:
				self::__constructFull( $argv[0], $argv[1], $argv[2] );
		}
	}


	public function __constructBase() {
		$this->RoleToPermissionID = 0;
		$this->RoleID = 0;
		$this->PermissionID = 0;
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramRoleToPermissionID,$paramRoleID,$paramPermissionID) {
		$this->RoleToPermissionID = $paramRoleToPermissionID;
		$this->RoleID = $paramRoleID;
		$this->PermissionID = $paramPermissionID;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getRoleToPermissionID(){
		return $this->RoleToPermissionID;
	}
	public function setRoleToPermissionID($value){
		$this->RoleToPermissionID = $value;
	}
	public function getRoleID(){
		return $this->RoleID;
	}
	public function setRoleID($value){
		$this->RoleID = $value;
	}
	public function getPermissionID(){
		return $this->PermissionID;
	}
	public function setPermissionID($value){
		$this->PermissionID = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setRoleToPermissionID($row['RoleToPermissionID']);
		 $this->setRoleID($row['RoleID']);
		 $this->setPermissionID($row['PermissionID']);
		}
	}


	public function save() {
		if ($this->getRoleToPermissionID() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_Add(?,?)');
		$arg1 = $this->getRoleID();
		$arg2 = $this->getPermissionID();
		$stmt->bind_param('ii',$arg1,$arg2);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_Update(?,?,?)');
		$arg1 = $this->getRoleToPermissionID();
		$arg2 = $this->getRoleID();
		$arg3 = $this->getPermissionID();
		$stmt->bind_param('iii',$arg1,$arg2,$arg3);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$rolestopermissions = new Rolestopermissions($row['RoleToPermissionID'],$row['RoleID'],$row['PermissionID']);
				$arr[] = $rolestopermissions;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_Remove(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramRoleToPermissionID,$paramRoleID,$paramPermissionID) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_rolestopermissions_Search(?,?,?)');
		$arg1 = Rolestopermissions::setNullValue($paramRoleToPermissionID);
		$arg2 = Rolestopermissions::setNullValue($paramRoleID);
		$arg3 = Rolestopermissions::setNullValue($paramPermissionID);
		$stmt->bind_param('iii',$arg1,$arg2,$arg3);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$rolestopermissions = new Rolestopermissions($row['RoleToPermissionID'],$row['RoleID'],$row['PermissionID']);
				$arr[] = $rolestopermissions;
			}
			return $arr;
		}
		else {
			die("The query yielded zero results.No rows found.");
		}
	}
}
