/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/18/2017
Description:	Creates the accounts table and respective stored procedures

*/


USE smithadb;



--------------------------------------------------------------
-- Create table
--------------------------------------------------------------



CREATE TABLE `smithadb`.`accounts` (
AccountID INT AUTO_INCREMENT,
FirstName VARCHAR(255),
LastName VARCHAR(255),
Email VARCHAR(255),
Password VARCHAR(255),
RoleID INT,
TeamID INT,
CONSTRAINT pk_accounts_AccountID PRIMARY KEY (AccountID)
);


--------------------------------------------------------------
-- Create default SCRUD sprocs for this table
--------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_Load`
(
	 IN paramAccountID INT
)
BEGIN
	SELECT
		`accounts`.`AccountID` AS `AccountID`,
		`accounts`.`FirstName` AS `FirstName`,
		`accounts`.`LastName` AS `LastName`,
		`accounts`.`Email` AS `Email`,
		`accounts`.`Password` AS `Password`,
		`accounts`.`RoleID` AS `RoleID`,
		`accounts`.`TeamID` AS `TeamID`
	FROM `accounts`
	WHERE 		`accounts`.`AccountID` = paramAccountID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_LoadAll`()
BEGIN
	SELECT
		`accounts`.`AccountID` AS `AccountID`,
		`accounts`.`FirstName` AS `FirstName`,
		`accounts`.`LastName` AS `LastName`,
		`accounts`.`Email` AS `Email`,
		`accounts`.`Password` AS `Password`,
		`accounts`.`RoleID` AS `RoleID`,
		`accounts`.`TeamID` AS `TeamID`
	FROM `accounts`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_Add`
(
	 IN paramFirstName VARCHAR(255),
	 IN paramLastName VARCHAR(255),
	 IN paramEmail VARCHAR(255),
	 IN paramPassword VARCHAR(255),
	 IN paramRoleID INT,
	 IN paramTeamID INT
)
BEGIN
	INSERT INTO `accounts` (FirstName,LastName,Email,Password,RoleID,TeamID)
	VALUES (paramFirstName, paramLastName, paramEmail, paramPassword, paramRoleID, paramTeamID);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_Update`
(
	IN paramAccountID INT,
	IN paramFirstName VARCHAR(255),
	IN paramLastName VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramRoleID INT,
	IN paramTeamID INT
)
BEGIN
	UPDATE `accounts`
	SET FirstName = paramFirstName
		,LastName = paramLastName
		,Email = paramEmail
		,Password = paramPassword
		,RoleID = paramRoleID
		,TeamID = paramTeamID
	WHERE		`accounts`.`AccountID` = paramAccountID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_Delete`
(
	IN paramAccountID INT
)
BEGIN
	DELETE FROM `accounts`
	WHERE		`accounts`.`AccountID` = paramAccountID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_accounts_Search`
(
	IN paramAccountID INT,
	IN paramFirstName VARCHAR(255),
	IN paramLastName VARCHAR(255),
	IN paramEmail VARCHAR(255),
	IN paramPassword VARCHAR(255),
	IN paramRoleID INT,
	IN paramTeamID INT
)
BEGIN
	SELECT
		`accounts`.`AccountID` AS `AccountID`,
		`accounts`.`FirstName` AS `FirstName`,
		`accounts`.`LastName` AS `LastName`,
		`accounts`.`Email` AS `Email`,
		`accounts`.`Password` AS `Password`,
		`accounts`.`RoleID` AS `RoleID`,
		`accounts`.`TeamID` AS `TeamID`
	FROM `accounts`
	WHERE
		COALESCE(accounts.`AccountID`,0) = COALESCE(paramAccountID,accounts.`AccountID`,0)
		AND COALESCE(accounts.`FirstName`,'') = COALESCE(paramFirstName,accounts.`FirstName`,'')
		AND COALESCE(accounts.`LastName`,'') = COALESCE(paramLastName,accounts.`LastName`,'')
		AND COALESCE(accounts.`Email`,'') = COALESCE(paramEmail,accounts.`Email`,'')
		AND COALESCE(accounts.`Password`,'') = COALESCE(paramPassword,accounts.`Password`,'')
		AND COALESCE(accounts.`RoleID`,0) = COALESCE(paramRoleID,accounts.`RoleID`,0)
		AND COALESCE(accounts.`TeamID`,0) = COALESCE(paramTeamID,accounts.`TeamID`,0);
END //
DELIMITER ;


