/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/18/2017
Description:	Creates the prioritytypes table and respective stored procedures

*/


USE smithadb;



-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `smithadb`.`prioritytypes` (
PriorityTypeID INT AUTO_INCREMENT,
PriorityType VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_prioritytypes_PriorityTypeID PRIMARY KEY (PriorityTypeID)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_Load`
(
	 IN paramPriorityTypeID INT
)
BEGIN
	SELECT
		`prioritytypes`.`PriorityTypeID` AS `PriorityTypeID`,
		`prioritytypes`.`PriorityType` AS `PriorityType`,
		`prioritytypes`.`Description` AS `Description`
	FROM `prioritytypes`
	WHERE 		`prioritytypes`.`PriorityTypeID` = paramPriorityTypeID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_LoadAll`()
BEGIN
	SELECT
		`prioritytypes`.`PriorityTypeID` AS `PriorityTypeID`,
		`prioritytypes`.`PriorityType` AS `PriorityType`,
		`prioritytypes`.`Description` AS `Description`
	FROM `prioritytypes`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_Add`
(
	 IN paramPriorityType VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `prioritytypes` (PriorityType,Description)
	VALUES (paramPriorityType, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_Update`
(
	IN paramPriorityTypeID INT,
	IN paramPriorityType VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `prioritytypes`
	SET PriorityType = paramPriorityType
		,Description = paramDescription
	WHERE		`prioritytypes`.`PriorityTypeID` = paramPriorityTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_Delete`
(
	IN paramPriorityTypeID INT
)
BEGIN
	DELETE FROM `prioritytypes`
	WHERE		`prioritytypes`.`PriorityTypeID` = paramPriorityTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_prioritytypes_Search`
(
	IN paramPriorityTypeID INT,
	IN paramPriorityType VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`prioritytypes`.`PriorityTypeID` AS `PriorityTypeID`,
		`prioritytypes`.`PriorityType` AS `PriorityType`,
		`prioritytypes`.`Description` AS `Description`
	FROM `prioritytypes`
	WHERE
		COALESCE(prioritytypes.`PriorityTypeID`,0) = COALESCE(paramPriorityTypeID,prioritytypes.`PriorityTypeID`,0)
		AND COALESCE(prioritytypes.`PriorityType`,'') = COALESCE(paramPriorityType,prioritytypes.`PriorityType`,'')
		AND COALESCE(prioritytypes.`Description`,'') = COALESCE(paramDescription,prioritytypes.`Description`,'');
END //
DELIMITER ;


