/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/18/2017
Description:	Creates the commentstatustypes table and respective stored procedures

*/


USE smithadb;



-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `smithadb`.`commentstatustypes` (
CommentStatusTypeID INT AUTO_INCREMENT,
CommentStatusType VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_commentstatustypes_CommentStatusTypeID PRIMARY KEY (CommentStatusTypeID)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_Load`
(
	 IN paramCommentStatusTypeID INT
)
BEGIN
	SELECT
		`commentstatustypes`.`CommentStatusTypeID` AS `CommentStatusTypeID`,
		`commentstatustypes`.`CommentStatusType` AS `CommentStatusType`,
		`commentstatustypes`.`Description` AS `Description`
	FROM `commentstatustypes`
	WHERE 		`commentstatustypes`.`CommentStatusTypeID` = paramCommentStatusTypeID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_LoadAll`()
BEGIN
	SELECT
		`commentstatustypes`.`CommentStatusTypeID` AS `CommentStatusTypeID`,
		`commentstatustypes`.`CommentStatusType` AS `CommentStatusType`,
		`commentstatustypes`.`Description` AS `Description`
	FROM `commentstatustypes`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_Add`
(
	 IN paramCommentStatusType VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `commentstatustypes` (CommentStatusType,Description)
	VALUES (paramCommentStatusType, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_Update`
(
	IN paramCommentStatusTypeID INT,
	IN paramCommentStatusType VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `commentstatustypes`
	SET CommentStatusType = paramCommentStatusType
		,Description = paramDescription
	WHERE		`commentstatustypes`.`CommentStatusTypeID` = paramCommentStatusTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_Delete`
(
	IN paramCommentStatusTypeID INT
)
BEGIN
	DELETE FROM `commentstatustypes`
	WHERE		`commentstatustypes`.`CommentStatusTypeID` = paramCommentStatusTypeID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `smithadb`.`usp_commentstatustypes_Search`
(
	IN paramCommentStatusTypeID INT,
	IN paramCommentStatusType VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`commentstatustypes`.`CommentStatusTypeID` AS `CommentStatusTypeID`,
		`commentstatustypes`.`CommentStatusType` AS `CommentStatusType`,
		`commentstatustypes`.`Description` AS `Description`
	FROM `commentstatustypes`
	WHERE
		COALESCE(commentstatustypes.`CommentStatusTypeID`,0) = COALESCE(paramCommentStatusTypeID,commentstatustypes.`CommentStatusTypeID`,0)
		AND COALESCE(commentstatustypes.`CommentStatusType`,'') = COALESCE(paramCommentStatusType,commentstatustypes.`CommentStatusType`,'')
		AND COALESCE(commentstatustypes.`Description`,'') = COALESCE(paramDescription,commentstatustypes.`Description`,'');
END //
DELIMITER ;


